dubbo:
  application:
      name: seata-business
      logger: slf4j
  protocol:
    name: dubbo
    port: 20900
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
  provider:
    threads: 500
    threadpool: fixed
    queues: 200
spring:
  datasource:
    username: nacos
    password: 123456
    url: jdbc:mysql://localhost:3306/nacos?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true
