server:
  port: 8081
dubbo:
  application:
      name: dubbo-consumer
      logger: slf4j
  consumer:
    threads: 500
    threadpool: cached
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos


